/* Generate a PWM with timer A1 (TA1)
 * Diferent duty cycles to Capture Compare Unit 1 and 2
 * pins 2.1 and 2.2 have the same (TA1.1) pwm generated by Capture Compare Unit 1
 * pins 2.4 and 2.5 have the same (TA1.2) ppwm generated by Capture Compare Unit 2
 * 
*/

#include <msp/msp430g2553.h>


main() {
	const int DUTY[2] = {50, 30}; // %

	// select pwm output pins
	// select p2.1 and p2.2 to TA1.1 and p2.4 and p2.5 to TA1.2
	P2DIR |= BIT1 + BIT2 + BIT4 + BIT5; // select output direction
	P2SEL |= BIT1 + BIT2 + BIT4 + BIT5; // select special function (PWM)

	//DCO configuration
	DCOCTL = DCO1 + DCO0; // divider (divide nominal clock) and modulator (takes a clock between the actual nominal clock and the next)
	BCSCTL1 = RSEL1; //nominal clock
	// 150 kHz to cpu system clock

	//timer Capture/Compare configuration
	TA1CCR0 = 37500 / 1000; //PWM period of 1ms
	TA1CCR1 = TA1CCR0 / (100 / DUTY[0]); //count limit (16 bits) pin 2.1 and 2.2 duty cicle
	TA1CCR2 = TA1CCR0 / (100 / DUTY[1]); //count limit (16 bits) pin 2.4 and 2.5 duty cicle
	TA1CCTL1 = OUTMOD_7; //select outputmod reset/set -----\_____ to Capture Compare Unit 1
	TA1CCTL2 = OUTMOD_7; //select outputmod reset/set -----\_____ to Capture Compare Unit 2

	//timer A configuration
	TA1CTL = TASSEL_2 + ID_2 + MC_1; //control register
}

